apiVersion: v1
kind: Pod
metadata:
  name: buildkit-build
spec:
  hostAliases:
    - ip: "10.102.193.8"   # <-- Your Ingress controller's service IP
      hostnames:
        - "registry.local.test"
  containers:
  - name: buildkit
    image: moby/buildkit:rootless
    env:
    - name: BUILDKITD_FLAGS
      value: "--oci-worker-no-process-sandbox"
    command: ["/bin/sh"]
    args:
    - "-c"
    - |
      # Install git
      apk add --no-cache git
      
      # Clone the repository
      git clone https://github.com/chuantap/pg /tmp/source
      cd /tmp/source
      
      # Create Docker config
      mkdir -p ~/.docker
      echo '{"auths":{"registry.local.test":{"insecure":true}}}' > ~/.docker/config.json
      
      # Build using local context
      buildctl-daemonless.sh build \
        --frontend dockerfile.v0 \
        --local context=. \
        --local dockerfile=. \
        --output type=image,name=registry.local.test/whatismyip-buildkit:latest,push=true,registry.insecure=true \
        --opt filename=Dockerfile
  restartPolicy: Never
  